-- Replaced by Laravel migrations: every database change is now a migration in
-- database/migrations, applied to live with `php artisan migrate --force`
-- (see README.md, "Database changes"). No SQL was ever applied from this file.
